name: CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  # Job de Continuous Integration (CI)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint

  # Job de Continuous Delivery (CD) - Simulado
  cd:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulating packaging
        run: zip projeto.zip *.py README.md

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: projeto.zip
          path: projeto.zip

  # Job opcional de "Deploy" que simula o uso do pacote gerado
  deploy:
    runs-on: ubuntu-latest
    needs: cd
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: projeto.zip

      - name: Listando conteúdo do artefato
        run: unzip -l projeto.zip
