name: Continuos Integration - Somativa 1
on:
  pull_request:
    branches:
      -main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: zip-teste.zip

      - name: Display structure of downloaded files
        run: ls -R

